// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXa5Kovg2XJ4a5KSSeKBCjyFMMrDW9Q4',
    appId: '1:979089203708:web:7fabe3d48fdee40d00d279',
    messagingSenderId: '979089203708',
    projectId: 'edutime-7e6ff',
    authDomain: 'edutime-7e6ff.firebaseapp.com',
    storageBucket: 'edutime-7e6ff.firebasestorage.app',
    measurementId: 'G-K035XWHX02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBs5BujDehSMS5FEZMb-sce_WxUAJNut8',
    appId: '1:979089203708:android:40490336b9164c3c00d279',
    messagingSenderId: '979089203708',
    projectId: 'edutime-7e6ff',
    storageBucket: 'edutime-7e6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkPJrEfH3qMOkQJAQ_mEdXHjZAy1LiCc',
    appId: '1:979089203708:ios:1272081f12e3876800d279',
    messagingSenderId: '979089203708',
    projectId: 'edutime-7e6ff',
    storageBucket: 'edutime-7e6ff.firebasestorage.app',
    iosClientId: '979089203708-pmnam864stlmp5mrnul6371r3fnt744j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjkPJrEfH3qMOkQJAQ_mEdXHjZAy1LiCc',
    appId: '1:979089203708:ios:1272081f12e3876800d279',
    messagingSenderId: '979089203708',
    projectId: 'edutime-7e6ff',
    storageBucket: 'edutime-7e6ff.firebasestorage.app',
    iosClientId: '979089203708-pmnam864stlmp5mrnul6371r3fnt744j.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZXa5Kovg2XJ4a5KSSeKBCjyFMMrDW9Q4',
    appId: '1:979089203708:web:c63634b23c18946900d279',
    messagingSenderId: '979089203708',
    projectId: 'edutime-7e6ff',
    authDomain: 'edutime-7e6ff.firebaseapp.com',
    storageBucket: 'edutime-7e6ff.firebasestorage.app',
    measurementId: 'G-YQ1C0PCTJB',
  );
}
